{{- if .Values._namespace.etcd }}
{{- $src := lookup "v1" "Secret" .Release.Namespace (printf "%s-admin-kubeconfig" .Release.Name) }}
{{- if and $src $src.data (index $src.data "admin.conf") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-user-kubeconfig
  labels:
    apps.cozystack.io/user-secret: "true"
    apps.cozystack.io/application.group: apps.cozystack.io
    apps.cozystack.io/application.kind: KubernetesSwitchcloud
    apps.cozystack.io/application.name: {{ trimPrefix "kubernetes-switchcloud-" .Release.Name }}
    internal.cozystack.io/managed-by-cozystack: "true"
    internal.cozystack.io/tenantresource: "true"
type: Opaque
data:
  kubeconfig: {{ index $src.data "admin.conf" }}
{{- end }}
{{- end }}
