---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: kubernetes-switchcloud-platform
  namespace: cozy-system
spec:
  url: oci://ghcr.io/aenix-org
  charts:
    - name: kubernetes-switchcloud-platform
      version: ">=0.0.1"
      type: system
---
apiVersion: cozystack.io/v1alpha1
kind: Package
metadata:
  name: cozystack.kubernetes-switchcloud-platform
  namespace: cozy-system
spec:
  variant: default
