{{- if and .Values.addons.clusterAutoscaler.enabled .Values._namespace.etcd }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cluster-autoscaler
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-cluster-autoscaler
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cluster-autoscaler
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cluster-autoscaler
        policy.cozystack.io/allow-to-apiserver: "true"
    spec:
      enableServiceLinks: false
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: "NoSchedule"
      initContainers:
      {{- include "kubernetes-switchcloud.waitForAdminKubeconfig" $ | nindent 6 }}
      containers:
      - image: {{ .Values.addons.clusterAutoscaler.image | quote }}
        name: cluster-autoscaler
        resources:
          limits:
            cpu: 512m
            memory: 512Mi
          requests:
            cpu: 125m
            memory: 128Mi
        command:
        - /cluster-autoscaler
        args:
        - --cloud-provider=clusterapi
        - --enforce-node-group-min-size=true
        - --ignore-daemonsets-utilization=true
        - --ignore-mirror-pods-utilization=true
        - --scale-down-delay-after-add={{ .Values.addons.clusterAutoscaler.scaleDownDelayAfterAdd }}
        - --scale-down-unneeded-time={{ .Values.addons.clusterAutoscaler.scaleDownUnneededTime }}
        - --max-node-provision-time={{ .Values.addons.clusterAutoscaler.maxNodeProvisionTime }}
        - --scan-interval=10s
        - --force-delete-unregistered-nodes=true
        - --kubeconfig=/etc/kubernetes/kubeconfig/super-admin.svc
        - --clusterapi-cloud-config-authoritative
        - --node-group-auto-discovery=clusterapi:namespace={{ .Release.Namespace }},clusterName={{ .Release.Name }}
        volumeMounts:
        - mountPath: /etc/kubernetes/kubeconfig
          name: kubeconfig
          readOnly: true
      volumes:
      - secret:
          secretName: {{ .Release.Name }}-admin-kubeconfig
          optional: true
        name: kubeconfig
      serviceAccountName: {{ .Release.Name }}-cluster-autoscaler
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cluster-autoscaler
  namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-cluster-autoscaler
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
    - cluster.x-k8s.io
    resources:
    - machinedeployments
    - machinedeployments/scale
    - machines
    - machinesets
    - machinepools
    verbs:
    - get
    - list
    - update
    - watch
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    resources:
    - openstackmachinetemplates
    verbs:
    - get
    - list
    - update
    - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-cluster-autoscaler
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-cluster-autoscaler
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-cluster-autoscaler
  namespace: {{ .Release.Namespace }}
{{- end }}
