apiVersion: v1
kind: ServiceAccount
metadata:
  name: talos-trustd-router
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: talos-trustd-router
rules:
- apiGroups: [""]
  resources: [services]
  verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: talos-trustd-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: talos-trustd-router
subjects:
- kind: ServiceAccount
  name: talos-trustd-router
  namespace: {{ .Release.Namespace }}
