apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ocirepository.yaml
  - packagesources/capi-provider-bootstrap-talos.yaml
  - packagesources/capi-provider-infra-openstack.yaml
  - packagesources/kubernetes-switchcloud.yaml
