---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.capi-provider-infra-openstack
spec:
  sourceRef:
    kind: OCIRepository
    name: kubernetes-switchcloud-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    - cozystack.capi-operator
    components:
    - name: capi-providers-infraprovider-openstack
      path: system/capi-providers-infraprovider-openstack
      install:
        privileged: true
        namespace: cozy-cluster-api
        releaseName: capi-providers-infraprovider-openstack
