---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.kubernetes-switchcloud
spec:
  sourceRef:
    kind: OCIRepository
    name: kubernetes-switchcloud-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    - cozystack.capi-operator
    - cozystack.capi-provider-core
    - cozystack.capi-provider-cp-kamaji
    components:
    - name: kubernetes-switchcloud-rd
      path: system/kubernetes-switchcloud-rd
      install:
        namespace: cozy-system
        releaseName: kubernetes-switchcloud-rd
    - name: kubernetes-switchcloud
      path: apps/kubernetes-switchcloud
