---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.kubernetes-switchcloud
spec:
  sourceRef:
    kind: OCIRepository
    name: kubernetes-switchcloud-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    - cozystack.capi-operator
    - cozystack.capi-provider-core
    - cozystack.capi-provider-cp-kamaji
    - cozystack.capi-provider-bootstrap-talos
    - cozystack.capi-provider-infra-openstack
    components:
    - name: kubernetes-switchcloud
      path: apps/kubernetes-switchcloud
