{{- define "kubernetes-switchcloud.defaultCiliumValues" -}}
{{- $host := .Values._namespace.host }}
cilium:
  k8sServiceHost: {{ .Values.host | default (printf "%s.%s" .Release.Name $host) }}
  k8sServicePort: 443
  routingMode: tunnel
  MTU: 1350
  enableIPv4Masquerade: true
  ipv4NativeRoutingCIDR: ""
{{- end }}

{{- if and .Values.addons.cilium.enabled .Values._namespace.etcd }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Release.Name }}-cilium
  labels:
    cozystack.io/repository: system
    cozystack.io/target-cluster-name: {{ .Release.Name }}
    sharding.fluxcd.io/key: tenants
spec:
  releaseName: cilium
  chartRef:
    kind: ExternalArtifact
    name: cozystack-kubernetes-application-kubevirt-kubernetes-cilium
    namespace: cozy-system
  kubeConfig:
    secretRef:
      name: {{ .Release.Name }}-admin-kubeconfig
      key: super-admin.svc
  targetNamespace: cozy-cilium
  storageNamespace: cozy-cilium
  interval: 5m
  timeout: 10m
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    force: true
    remediation:
      retries: -1
  values:
    {{- toYaml (deepCopy .Values.addons.cilium.valuesOverride | mergeOverwrite (fromYaml (include "kubernetes-switchcloud.defaultCiliumValues" .))) | nindent 4 }}
  {{- if lookup "helm.toolkit.fluxcd.io/v2" "HelmRelease" .Release.Namespace .Release.Name }}
  dependsOn:
  - name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
