apiVersion: v2
name: cozy-kilo
description: Kilo WireGuard mesh for switchcloud tenant clusters (port of cozystack/packages/system/kilo)
version: 0.0.0 # Placeholder, the actual version will be automatically set during the build process
appVersion: "0.6.0"
