apiVersion: v2
name: cozy-talos-csr-signer
description: Talos trustd gRPC server for hosted control plane clusters
type: application
version: 0.0.0 # Placeholder, the actual version will be automatically set during the build process
appVersion: "0.5.0"
