apiVersion: v2
name: provider-id-setter
description: DaemonSet that sets spec.providerID on Kubernetes nodes running on OpenStack (Switch Cloud) via IMDS.
type: application
version: 0.1.2
appVersion: "0.4.2"
