apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-csr-signer
  labels:
    app: {{ .Release.Name }}-csr-signer
    talos.aenix.io/trustd: "true"
  annotations:
    talos.aenix.io/cluster-hostname: {{ required "clusterHostname is required" .Values.clusterHostname | quote }}
spec:
  selector:
    app: {{ .Release.Name }}-csr-signer
  ports:
  - name: trustd
    port: 50001
    targetPort: trustd
    protocol: TCP
