apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: kubernetes-switchcloud
  namespace: cozy-system
spec:
  url: oci://docker.io/999669
  charts:
    - name: cozy-capi-bootstrap-talos
      version: ">=0.0.0-0"
      type: system
    - name: cozy-capi-infraprovider-openstack
      version: ">=0.0.0-0"
      type: system
    - name: cozy-kubernetes-switchcloud
      version: ">=0.0.0-0"
      type: app
