---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kubernetes-switchcloud
  namespace: cozy-public
spec:
  type: oci
  url: oci://ghcr.io/aenix-org
  interval: 5m
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: kubernetes-switchcloud-capi-bootstrap-talos
  namespace: cozy-public
spec:
  chart: capi-bootstrap-talos
  version: "0.1.x"
  sourceRef:
    kind: HelmRepository
    name: kubernetes-switchcloud
    namespace: cozy-public
  interval: 5m
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: kubernetes-switchcloud-capi-infraprovider-openstack
  namespace: cozy-public
spec:
  chart: capi-infraprovider-openstack
  version: "0.1.x"
  sourceRef:
    kind: HelmRepository
    name: kubernetes-switchcloud
    namespace: cozy-public
  interval: 5m
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: kubernetes-switchcloud-talos-edge-router
  namespace: cozy-public
spec:
  chart: talos-edge-router
  version: "0.2.x"
  sourceRef:
    kind: HelmRepository
    name: kubernetes-switchcloud
    namespace: cozy-public
  interval: 5m
