---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kubernetes-switchcloud-packages
  namespace: cozy-system
spec:
  interval: 5m
  url: oci://ghcr.io/aenix-org/charts/kubernetes-switchcloud
  ref:
    semver: ">=0.3.0"
---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: kubernetes-switchcloud
  namespace: cozy-system
spec:
  sourceRef:
    kind: OCIRepository
    name: kubernetes-switchcloud-packages
    namespace: cozy-system
  variants:
    - name: default
      components:
        - name: kubernetes-switchcloud
          path: kubernetes-switchcloud
